# Generated by Django 3.2.9 on 2021-12-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='ativo',
        ),
    ]
